version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2

workflows:
  sample:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          force: true
          requires:
            - node/test
          filters:
            branches:
              only: master
